---
title: "DBDA.X404.(8) - Assignment#1" 
author: "Omer Orhan"
date: "5 Ekim 2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#QUESTION1;
#What are the different steps of data analysis
#and what is done during each step

#answer;
#The steps of data analysis are Design, Obtain Data, Data Prep, Analyze, Fine Tune,present.

# Design: Gather requirements
# Obtain Data: Data collection
# Data Prep: Data exploration, preview, and selection, preprocessing, cleaning and preparation.
# Analyze: Data normalization and transformation
# Fine Tune: Gather and analyze results
# Present: present the results

```


```{r}
#QUESTION2. What are the different ways to create a vector in R?
x <- 1:7; x
x <- seq(1, 3, by=0.2); x
x <- c(1, 5.4, TRUE, "hello"); x
```

```{r}
#QUESTION3:Create the following vector and check the class (‘x’,’x’, ‘x’, 1,3,5,7,9,2,4,6,8,10)
Q3 <- c(rep(c('x'), times = 3),1:10)
Q3
class(Q3)


```

```{r}
#QUESTION4:Create a vector of positive odd integers less than 100
x<-seq(1,100, by =2); x

```

```{r}
#QUESTION5:Remove the values greater than 60 and less than 80
x2 <- x[!x %in% 60:80]; x2

```

```{r}
#QUESTION6:Write a function to return standard deviation, mean, and median of the vector. Verify with example.
 Q6 <-function(input) {
     
     sd= sd(input)
     med = median(input)
     mea = mean(input)
     output<-list("standart deviation:"=sd,"mean="=med,"median="=mea)
     return(output) }
 
 x<-seq(1,100, by =2); 
 x2 <- x[!x %in% 60:80]
 res <- Q6(x2)
 res

```

```{r}
#QUESTION7:Create two matrices of the from the given set of numbers} in two ways X1 = {2,3,7,1,6,2,3,5,1} and x2 ={3,2,9,0,7,8,5,8,2}

mat1 = matrix(c(2,3,7,1,6,2,3,5,1), nrow=3, ncol=3, byrow = TRUE) 
mat1
mat2 = matrix(c(3,2,9,0,7,8,5,8,2), nrow=3, ncol=3) 
mat2

```

```{r}
#QUESTION8:Find the matrix product
 matProduct <- mat1 %*% mat2
 matProduct

```

```{r}
#QUESTION9: Find the class of ‘iris’ dataframe, find the class of all the columns of ‘iris’ get the summary. Get rownames, column names. Get the number of rows and number of columns.

class(iris)
summary(iris)
colnames(iris)
rownames(iris)
nrow(iris)
ncol(iris)
```

```{r}
#QUESTION10: Get the last two rows in the last 2 columns from iris dataset.
iris[nrow(iris):(nrow(iris)-1),ncol(iris):(ncol(iris)-1)]
```

