---
title: "consumerComplaints"
author: "Omer Orhan"
date: "11 Kasım 2018"
output:
  html_document: default
  pdf_document: default
---

```{r}
#http://www.rpubs.com/ykimmate14/154171
options(warn=-1)
library(ggplot2); 
library(RColorBrewer);
library(gridExtra)
library(devtools)
library(wordcloud)
NofRow <- function(data, c){
    list1 <- unique(data[,c])
    list2 <- list()
    for(i in 1:length(list1)){
        list2 <- c(list2, sum(data[,2] %in% list1[i]))
    }
    result <- data.frame(uniqueV = list1, count = unlist(list2))
    return(result)
}

#Load the dataset

df <- read.csv("c:/Consumer_Complaints.csv" ,nrows=2000, header= TRUE, stringsAsFactors = F)

write.csv(df, file = "C:/Users/omer/Consumer_Complaints_2000.csv")
```


```{r}
#Exploratory Analysis
#create a word cloud that shows most frequently complained product
df$Date.received <- as.Date(df$Date.received, format = "%m/%d/%Y")
df$Date.sent.to.company <- as.Date(df$Date.sent.to.company, format = "%m/%d/%Y")


```

```{r}
#create a bar chart that shows most frequently complained product
set.seed(1)

clouddf1 <- NofRow(df, 2)
print(df)
wordcloud(clouddf1[,1], clouddf1[,2], scale = c(3,.8), colors=brewer.pal(12,"Accent"))

```

```{r}
colcount.product = length(unique(df$Product))
getPalette = colorRampPalette(brewer.pal(8, "Set2"))
str(df)
print(colcount.product)
ggplot(df, aes(x= Product)) + geom_bar(aes(fill = factor(Product))) + theme(axis.text.x = element_blank()) +
    scale_fill_manual(values = getPalette(colcount.product))
```

