---
title: "visa"
author: "Omer Orhan"
date: "29 Ekim 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#import library
library(dplyr)
library(ggplot2)
#loading data
dataset <- read.csv("c:/us_perm_visas.csv", header = TRUE, sep = ",",
stringsAsFactors= FALSE)

#seeing first 10 rows
#head(dataset)

#using columns
#attach(dataset)

#seeing columnnames and types
str(dataset)

perres <- dataset[, c("decision_date","foreign_worker_info_birth_country","class_of_admission","country_of_citizenship","case_received_date","case_status"
,"country_of_citizenship","employer_city","employer_state","foreign_worker_info_education","foreign_worker_info_major","foreign_worker_info_birth_country","wage_offer_from_9089","us_economic_sector")]

```
```{r}
#getting  "decision_date","foreign_worker_info_birth_country columns
CountryAndYear <- dataset[, c("decision_date","foreign_worker_info_birth_country")]
#cleaning data
 CountryAndYear[CountryAndYear==""] <- NA
CountryAndYear <- na.omit(CountryAndYear)

#cleaning date format
CountryAndYear$decision_date <- format(as.Date(CountryAndYear$decision_date, "%Y-%m-%d"), "%Y")

#changing column names
colnames(CountryAndYear)=c("YEAR", "APPLICANTS")

#grouping data by year
CountByCountry <- aggregate(cbind(count = APPLICANTS) ~ APPLICANTS, 
          data = CountryAndYear, 
          FUN = function(x){NROW(x)})

#changing columns
colnames(CountByCountry)=c("COUNTRY", "APPLICANTCOUNT")

#########################################
#descriptive analysis
#mean
mean(CountByCountry$APPLICANTCOUNT, na.rm = TRUE)

#median
median(CountByCountry$APPLICANTCOUNT, na.rm = TRUE)

# get both the min and max values
range(CountByCountry$APPLICANTCOUNT, na.rm = FALSE)

#Percentiles
fivenum(CountByCountry$APPLICANTCOUNT)

# default quantile() percentiles are 0%, 25%, 50%, 75%, and 100% 
quantile(CountByCountry$APPLICANTCOUNT, na.rm = TRUE)

# we can quickly compute the difference between the 1st and 3rd quantile
IQR(CountByCountry$APPLICANTCOUNT)

##################################
# showing with gplot
qplot(COUNTRY, APPLICANTCOUNT, data=CountByCountry)

#showing table
print(CountByCountry)


#removing outliners
CountByCountry <- CountByCountry[-which(CountByCountry$APPLICANTCOUNT %in% boxplot.stats(CountByCountry$APPLICANTCOUNT)$out), ]

#showing table again
print(CountByCountry)

# showing with gplot again
qplot(COUNTRY, APPLICANTCOUNT, data=CountByCountry[1:5,])

#ordering by count
CountByCountry[order(CountByCountry$APPLICANTCOUNT),]

#getting top5 coun
head(CountByCountry)

```

```{r}

```

```{r}
#How many people applied and  how many people got approved over 2012-2017?

#getting all of the status
unique(dataset$case_status)
#getting only Certified data
status_certified <- subset(dataset, dataset$case_status=="Certified")
#getting count of Certified applicants
nrow(status_certified)
#getting count of Denied applicants
nrow(subset(dataset, dataset$case_status=="Denied"))
#getting all of the countries
unique(dataset$foreign_worker_info_birth_country)
#getting all of the sectors
unique(dataset$us_economic_sector)
#
CountByCountry <- aggregate(cbind(count = dataset$foreign_worker_info_birth_country) ~ foreign_worker_info_birth_country, 
          data = dataset, 
          FUN = function(x){NROW(x)})

CountByCountry[order(CountByCountry$count, decreasing = TRUE),]

```

```{r}
#What is the relation between employers’ state and U.S. economic sector?
library(dplyr)
library(ggplot2)
#getting "employer_state","us_economic_sector" columns
stateAndSectors <- dataset[,c("employer_state","us_economic_sector")]
#cleaning data
stateAndSectors[stateAndSectors==""] <- NA
stateAndSectors <- na.omit(stateAndSectors)
#grouping states and sectors
stateAndSectorsGrouped <- stateAndSectors %>% group_by(employer_state, us_economic_sector) %>% summarise(Freq = n())
#ordering by freq
stateAndSectorsGrouped <- stateAndSectorsGrouped[order(stateAndSectorsGrouped$Freq,decreasing = TRUE),]
#top10
stateAndSectorsGroupedTop10 <- stateAndSectorsGrouped[1:10,]
#showing in graph
 ggplot(stateAndSectorsGroupedTop10, aes(x=us_economic_sector, y= Freq)) +     geom_point(aes(col=employer_state), size=3)+labs(title="Sector Frequency", x="Sector", y="Frequency")	

##What is the relation between employers’ state and U.S. economic sector in CALIFORNIA?
#getting applicants of California 
stateAndSectorsCalifornia <- subset(stateAndSectorsGrouped, employer_state=="CALIFORNIA" , select=c(employer_state,Freq))
#top5 
stateAndSectorsCalifornia <- subset(stateAndSectorsGrouped, employer_state=="CALIFORNIA" , select=c(us_economic_sector,Freq))
#top5
stateAndSectorsCalifornia <- stateAndSectorsCalifornia[1:5,]
#showing within graph
ggplot(data=stateAndSectorsCalifornia, y="Frequency", aes(x=us_economic_sector, y=Freq)) +
    geom_bar(stat="identity",color="blue")+labs(title="Sector Frequency in California", x="Sector", y="Frequency")

	
```

```{r}
wageYear <- dataset[,c("decision_date","wage_offer_from_9089","job_info_work_state","us_economic_sector")]
#wageYear$decision_date <- format(as.Date(wageYear$decision_date, "%Y-%m-%d"), "%Y")

#Lets see sample data for the the dataset by running below command which selects every 5th row starting from 1st row.
wageYear[seq(from=1, to=60, by=5),]
#evaluateTheData
class(wageYear)
str(wageYear)
#data cleaning
 wageYear[wageYear==""] <- NA
wageYear <- na.omit(wageYear)
#Basic Data Exploration and Visualization
wageYear$wage_offer_from_9089 <- as.numeric(wageYear$wage_offer_from_9089) 
wageYear$decision_date <- as.Date(wageYear$decision_date) 
wageYear[, 'job_info_work_state'] <- as.factor(wageYear[, 'job_info_work_state'])
wageYear[, 'us_economic_sector'] <- as.factor(wageYear[, 'us_economic_sector'])
#First, we will visualize the variable Salaries against job_info_work_state, decision_date, us_economic_sector
par(mfrow=c(2,2))
plot(wageYear$wage_offer_from_9089 ~ wageYear$job_info_work_state)
plot(wageYear$wage_offer_from_9089 ~ wageYear$decision_date)
plot(wageYear$wage_offer_from_9089 ~ wageYear$us_economic_sector)
#Lets us lm function to fit the model and analyze what all attributes are significant.
lmfit = lm(wage_offer_from_9089 ~ ., data = wageYear)
summary(lmfit)
#If you look at coefficients section, We can seet that job_info_work_stateAR,us_economic_sectorAgribusiness,us_economic_sectorEducational Services,us_economic_sectorRetail show a significance (p-value < 0.05).
#Lets fit the independent variables with the dependent variable in the linear model.
lmfit = lm(wage_offer_from_9089 ~ job_info_work_state + us_economic_sector, data = wageYear)
summary(lmfit)
#As we fit selected predictor variables, it raises the f-statistic from 4.294 to 4.318.
par(mfrow=c(2,2))
plot(lmfit)
#Within the diagnostic plot, all the four plots indicate that the regression model follows the regression assumption.

```


